use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use vyp_api::normalize_package_name;

use crate::cache::venv::VenvLayout;

/// A distribution currently installed in a virtual environment.
#[derive(Debug, Clone)]
pub struct InstalledDist {
    /// Canonical (normalized) package name.
    pub name: String,
    pub version: String,
    /// Path to the `*.dist-info` directory.
    pub dist_info: PathBuf,
}

/// Scan a venv's site-packages for installed distributions (`*.dist-info`).
pub fn installed_distributions(layout: &VenvLayout) -> Vec<InstalledDist> {
    let mut out = Vec::new();
    let Ok(entries) = std::fs::read_dir(&layout.site_packages) else {
        return out;
    };
    for entry in entries.flatten() {
        let name = entry.file_name().to_string_lossy().to_string();
        let Some(stem) = name.strip_suffix(".dist-info") else { continue };
        // `{name}-{version}.dist-info`
        let Some((dist, version)) = stem.rsplit_once('-') else { continue };
        out.push(InstalledDist {
            name: normalize_package_name(dist),
            version: version.to_string(),
            dist_info: entry.path(),
        });
    }
    out
}

/// Find an installed distribution by (normalized) name.
pub fn find_installed(layout: &VenvLayout, name: &str) -> Option<InstalledDist> {
    let target = normalize_package_name(name);
    installed_distributions(layout)
        .into_iter()
        .find(|d| d.name == target)
}

/// Remove an installed distribution using its `RECORD` manifest. Returns the
/// number of files removed. Falls back to removing just the `.dist-info`
/// directory if no RECORD is present.
pub fn uninstall_dist(
    layout: &VenvLayout,
    dist: &InstalledDist,
) -> Result<usize, Box<dyn std::error::Error + Send + Sync>> {
    let record_path = dist.dist_info.join("RECORD");
    let mut removed = 0usize;
    let mut dirs: BTreeSet<PathBuf> = BTreeSet::new();

    if let Ok(content) = std::fs::read_to_string(&record_path) {
        for line in content.lines() {
            let rel = parse_record_path(line);
            if rel.is_empty() {
                continue;
            }
            let abs = resolve_record_path(&layout.site_packages, &rel);
            // Stay within the venv root as a safety guard against `..` escapes.
            if !abs.starts_with(&layout.root) {
                continue;
            }
            if abs.is_file() || abs.is_symlink() {
                if std::fs::remove_file(&abs).is_ok() {
                    removed += 1;
                }
                if let Some(parent) = abs.parent() {
                    dirs.insert(parent.to_path_buf());
                }
                // Remove interpreter-generated bytecode that RECORD doesn't list.
                removed += prune_pyc_for(&abs, &mut dirs);
            }
        }
    }

    // Always drop the dist-info directory itself.
    let _ = std::fs::remove_dir_all(&dist.dist_info);

    // Prune now-empty directories, deepest first.
    for dir in dirs.iter().rev() {
        let _ = std::fs::remove_dir(dir);
    }

    Ok(removed)
}

/// Remove `__pycache__/<stem>.*.pyc` bytecode generated for a removed `.py`
/// source file (PEP 3147 layout). Returns the number of files removed.
fn prune_pyc_for(py_file: &Path, dirs: &mut BTreeSet<PathBuf>) -> usize {
    if py_file.extension().and_then(|e| e.to_str()) != Some("py") {
        return 0;
    }
    let Some(stem) = py_file.file_stem().and_then(|s| s.to_str()) else {
        return 0;
    };
    let Some(parent) = py_file.parent() else { return 0 };
    let pycache = parent.join("__pycache__");
    let Ok(entries) = std::fs::read_dir(&pycache) else { return 0 };
    let prefix = format!("{}.", stem);
    let mut removed = 0;
    for entry in entries.flatten() {
        let name = entry.file_name().to_string_lossy().to_string();
        if name.starts_with(&prefix) && name.ends_with(".pyc") {
            if std::fs::remove_file(entry.path()).is_ok() {
                removed += 1;
            }
        }
    }
    dirs.insert(pycache);
    removed
}

/// Extract the path field (first CSV column) from a RECORD line.
fn parse_record_path(line: &str) -> String {
    let line = line.trim_end_matches(['\r', '\n']);
    if line.is_empty() {
        return String::new();
    }
    if let Some(rest) = line.strip_prefix('"') {
        // Quoted CSV field: read until the closing quote (handling "").
        let mut out = String::new();
        let mut chars = rest.chars().peekable();
        while let Some(c) = chars.next() {
            if c == '"' {
                if chars.peek() == Some(&'"') {
                    out.push('"');
                    chars.next();
                } else {
                    break;
                }
            } else {
                out.push(c);
            }
        }
        out
    } else {
        line.split(',').next().unwrap_or("").to_string()
    }
}

/// Resolve a RECORD-relative path (forward slashes, possibly with `../`)
/// against site-packages into an absolute, normalized path.
fn resolve_record_path(site_packages: &Path, rel: &str) -> PathBuf {
    let mut path = site_packages.to_path_buf();
    for seg in rel.split('/') {
        match seg {
            "" | "." => {}
            ".." => {
                path.pop();
            }
            other => path.push(other),
        }
    }
    path
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_plain_record_line() {
        assert_eq!(
            parse_record_path("requests/__init__.py,sha256=abc,123"),
            "requests/__init__.py"
        );
    }

    #[test]
    fn parse_quoted_record_line() {
        assert_eq!(
            parse_record_path("\"weird,name.py\",sha256=abc,5"),
            "weird,name.py"
        );
    }

    #[test]
    fn resolve_path_with_parent() {
        let sp = Path::new("/venv/lib/python3.11/site-packages");
        assert_eq!(
            resolve_record_path(sp, "../../../bin/black"),
            PathBuf::from("/venv/bin/black")
        );
    }
}
